[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jaxmg"
version = "0.1.0"
description = "Python wrapper around cuSolverMg with JAX support"
authors = [{ name = "Roeland Wiersema" }]
dependencies = ["pytest==8.2.1", "matplotlib>=3.10.3"]
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
jaxmg = [
    "bin/libpotrs.so",
    "bin/libpotrs_mp.so",
    "bin/libpotri.so",
    "bin/libsyevd.so",
    "bin/libsyevd_no_V.so",
]

[project.optional-dependencies]

cuda = ["jax[cuda12]>=0.6.2,<=0.7.2"]
docs = [
    "jax>=0.6.2,<=0.7.2",
    "mkdocs==1.6.1",
    "mkdocs-material==9.6.23",
    "mkdocstrings==0.30.1",
    "mkdocs-exclude==1.0.2",
    "mkdocs-ipynb==0.1.1",
    "hippogriffe==0.2.2",
]
